### ISSUE TITLE
Unknown junk notes on a specific song

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libOPNMIDI#91] opened 2019-06-07 10:50 UTC
Similar to #84, I guess...
During playback of a certain .mid, junk note (or notes, depending on chip count or emulator used) can be heard. I can't track where do they come from, in case of MAME 2608 or NP2 core they sustain to the end of a song, in case of Nuked 2612, with 3 FM cores, they terminate after ~15 seconds, starting at a different point of a song.
Tested with command-line midiplay.

[crap.zip](https://github.com/Wohlstand/libOPNMIDI/files/3265568/crap.zip) - .zip with recordings of different behaviours, song in question and my bank. I can't reproduce it with xg.wopn, maybe due to lack of GS instruments this song relies on?

**Comment by papiezak** [comment] 2019-06-07 19:05
I took a look at this song and my bank - the song uses instrument "Steel Guitar 2" (GS bank 32, patch 25), which I have in my bank. When muting this instrument, it falls back to standard GM "Steel Guitar" and the crap sounds are gone. 
However, steel guitar patch I have should not really cause any problem - I even took xg.wopn, added GS bank 32, dropped the instrument in question and still there were no junk sounds! So, something else must be wrong. 
[stguitar.opni.zip](https://github.com/Wohlstand/libOPNMIDI/files/3267259/stguitar.opni.zip) - instrument in question

**Comment by jpcima** [comment] 2019-06-08 16:43
It's reproducible easily in adlmidiplay, in realtime MIDI I couldn't do it.
It's not a very simple one to track, I'm going to give it a more detailed look.

**Comment by jpcima** [comment] 2019-06-12 12:40
I still don't exactly know but I found things.

- I can reduce the file to a smaller case, which doesn't have the Steel Guitar 2 but still produces the problem
- When I do not handle the sysex messages, even having GS mode forced on, the file plays correctly
- In the small case, file provided, problem can go away when you delete one among several tracks, not necessarily one track in particular

[n_toh03_lite_2.mid.gz](https://github.com/Wohlstand/libOPNMIDI/files/3281301/n_toh03_lite_2.mid.gz)

**Comment by papiezak** [comment] 2019-06-12 13:55
I see. It's really weird now, it would be great to get to know what happens at ~29 seconds mark of that song, when crap noises kick in. Maybe it's some weird NRPNs?

**Comment by jpcima** [comment] 2019-06-13 11:33
It's not NRPN. It has possibly to do with the 12th track "Standerd SET".
The track is switched to percussion by the GS Roland Percussion Channel sysex at the start.
Under the percussion mode, it seems this track is responsible for creating the noise.

**Comment by jpcima** [comment] 2019-06-13 12:05
I'm at the impression that note events do not process in proper order from the sequencer.

Starting note events on the track are:
```
    (:delta 145   (note-on 31 :velocity 120 :channel 10))
    (:delta 0     (note-on 37 :velocity 120 :channel 10))
    (:delta 1     (note-off 31 :velocity 0 :channel 10))
    (:delta 0     (note-off 37 :velocity 0 :channel 10))
```

but from opnmidiplay I have received:
```
NoteOff 31                      
Note On 31
NoteOff 37                      
Note On 37
```

**Comment by papiezak** [comment] 2019-06-13 14:22
On my side, I kinda managed to fix this problem in a weird way:
This song used "Sticks" percussion instrument, which ,on my bank, had operators 3 and 4 zeroed out (only release values for both operators were=15), after I duplicated values from OP2 into them, junk notes are no longer heard.

Yet, I don't have any idea why muting "Steel Guitar 2" caused "Sticks" to calm down...

**Comment by jpcima** [comment] 2019-06-13 15:43
Trace of register commands on a reduced example.

[debug.txt.gz](https://github.com/Wohlstand/libOPNMIDI/files/3286994/debug.txt.gz)
[n_toh03_lite_3.mid.gz](https://github.com/Wohlstand/libOPNMIDI/files/3286997/n_toh03_lite_3.mid.gz)

The releasing of channel 11 is suspect. The note-off, whether it's note-extended or isn't, is not writing anything to chip.

-> NoteOff Channel=10 Note=31 effective now
-> NoteOff Channel=10 Note=37 effective now

**Comment by jpcima** [comment] 2019-06-14 02:52
Ok this is current status. The test case is as reduced as I can make it. There are register dumps with text.
[tinycrap.tar.gz](https://github.com/Wohlstand/libOPNMIDI/files/3288801/tinycrap.tar.gz)

It's 2 notes in succession, the pad and then the sticks percussion.
The both of them play on the chip channel 0.

Strange thing: It's notable that the pitch of the drum is following the 1st note.
I can't explain the reason, hear it in opnmidiplay. The case "High.mid" is based on original, "Low.mid" is octaves lower.

You will first hear a pad as normal, and then the percussion is followed by sustaining noise. (note: the drum channel has sustain pedal on, when sustain pedal off this noise doesn't happen)

The register dumps don't give me a clue on what is happening in this case; none of the setup, or tuning of drum note has been affected, only affected is the first.
@Wohlstand do you understand a thing of this?

**Comment by papiezak** [comment] 2019-07-03 16:18
>The note-off, whether it's note-extended or isn't, is not writing anything to chip.
It's notable that the pitch of the drum is following the 1st note.
none of the setup, or tuning of drum note has been affected, only affected is the first.

@Wohlstand please ping if it's possible, these behaviours look very weird 🤔

**Comment by Wohlstand** [comment] 2019-07-03 22:20
In the past was a glitch that caused junk sound to appear because of silent drum voices was called and there are written into registers something to shut up the voice, but in fact, makes a glitch in some cases when something tries to deal with that channel. That may happen when actually silent instrument wasn't marked as silent and was written into registers.

**Comment by Wohlstand** [comment] 2023-11-25 00:23
There is a long time had been passed, many stuff had been reworked including disabling auto-arpeggio by default, and adding channel allocation modes. I ask, please verify the stuff carefully. This issue, seems, compeltely abandoned. If something weird will be found, please open a new issue with new stuff.

**Closed by Wohlstand** 2023-11-25 00:23 UTC
Labels: Need an analyze
