### ISSUE TITLE
Use Nuked OPN2 emulator

### ISSUE THREAD

**Issue by loki666** [Wohlstand/libOPNMIDI#1] opened 2017-10-06 11:46 UTC
https://github.com/nukeykt/Nuked-OPN2

**Comment by Wohlstand** [comment] 2017-10-06 11:49
Wow!
I have looked for more accurate emulator, but found nothing except of C and C++ versions of same emulator that used in the GME (I also would replace same emulator in GME too), thanks!

**Comment by loki666** [comment] 2017-10-06 11:56
thanks to @nukeykt

**Comment by Wohlstand** [comment] 2017-10-06 22:17
Okay, I will need some time to figure out how to deal with new emulator: how to correctly write registers data and how to correctly fetch sample data (for example, per every MIDI step I applying all register data in one run and then I taking 512 samples until I will do the next MIDI step. The current emulator has functions for a friendly dealing with the chip, but I don't think it is accurate even in case undocumented features are not implemented or implemented incorrectly, so, SSG-EG registers in my OPN2 bank editor gives almost no difference or I use it incorrectly).

**Comment by Wohlstand** [comment] 2017-10-27 09:28
Thanks to @nukeykt for explanation and referring the implementation that has necessary functions:
https://github.com/nukeykt/Nuked-OPN2/issues/4

**Comment by papiezak** [comment] 2017-11-21 18:08
Regarding Nuked emulator, is it OK that dual-core PC with 4 threads and 4 GB of RAM struggles to handle three YM3438 cores? It makes most MIDI's unlistenable (unless you convert them to .wav instead).

**Comment by Wohlstand** [comment] 2017-11-21 18:15
There are not real chips, and a way to paralelize emulation is not so creepy, look:
MIDI playing cycle has two steps: event processing and sound generation while waiting between ticks.
All chip emulators will receive their commands on first step. Then run parallel generation of sound chunks are will be stored into separate buffers. Then mix them and pass result to output.

**Comment by papiezak** [comment] 2017-11-21 18:26
OK, so in short that is my PC which isn't powerful enough to handle Nukeykt's amazing emulation?
Anyways, I'm looking forward MAME emu support, I can confirm it's WAY more accurate  than ancient GENS 2.10 (which was never a good emulation core in the first place), while being just as lightweight.

Oh, and there's fourth option - Aly James made his own YM2612 emu. Suposedly very accurate: http://www.alyjameslab.com/alyjameslabfmdrive.html However I don't know much about it.

**Comment by Wohlstand** [comment] 2017-11-21 18:26
A way to paralelize emulation is not so creepy, look:
MIDI playing cycle has two steps: event processing and sound generation while waiting between ticks.
All chip emulators will receive their commands on first step. Then run parallel generation of sound chunks are will be stored into separate buffers. Then mix them and pass result to output.

The reason why OPN2 emulator eats MUCH MORE power than same OPL3 emulator is more complex chip's internal that was simulated.

**Comment by Wohlstand** [comment] 2017-11-21 18:31
The reason I set Nuked to 3 chips because CPU core of 3.6 Ghz cant process it without choppy sound if more chips

**Comment by papiezak** [comment] 2017-11-21 18:32
Oh, I see. Thanks for answering.

**Comment by Wohlstand** [comment] 2017-11-21 18:37
Anyway, Ill review that emulator you have referred me and I'll replace GENS with it if it will eat small and will be more accurate than GENS.

**Comment by loki666** [comment] 2017-11-22 08:20
also make sure to enable compiler optimisations (at least for the OPN2 module), on NukedOPL3 it makes a huge speedup.

btw: if parallelisation of the emu isn't very difficult, you'll have a synchronisation point to wait for all the threads to complete (thread joining) which might defeat the benefit of running them in parallel.

**Comment by Wohlstand** [comment] 2017-11-22 08:43
About optimization: I just now ran debug and release (with -Os flag) assembly with 4 Nuked OPN2 emulated chips, and while I have at my job Intel Core i7-7700 with 3.6 Ghz per core, I have:
- debug build loads 12 % (~100% on one core)
- release build loads 7% (~58% on one core)

About synchronization: that obviously I must wait for all threads until begin to mix their output chunks. The goal of parallelization is ability to run more chips than one core allows. I will be able to run 8 chips without choppy playback even on quad-core CPU. Every core of 3.6 Ghz at me can process 3 chips without choppy playback, 4+ begins to sometimes chop the output sound (more chips, worse sound chop).

**Comment by Wohlstand** [comment] 2018-04-04 22:58
Since my OPN2 Bank Editor has the emulators benchmark which does same sound delay measurer operation with each emulator. Look the result from three emulators: Nuked, MAME and GENS:

![default](https://user-images.githubusercontent.com/6751442/38338986-9cef614e-3874-11e8-8410-fbd2ea509e8f.png)

As emulator has been accepted for optional usage, and since a moment when ability to toggle emulation core in run-time, I will close this as this task has been completed. So, feel free to test that stuff :wink:

**Closed by Wohlstand** 2018-04-04 22:58 UTC
Labels: enhancement
