### ISSUE TITLE
Correct internal sample rate (MAME core)

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libOPNMIDI#26] opened 2018-05-22 13:47 UTC
As I reported (Wohlstand/OPN2BankEditor#7), turns out that internal sample rate doesn't match YM2612's real sample rate (53267 Hz?). Therefore many instruments such as hi-hats, cymbals, triangles, etc don't sound as they should.

**Comment by Wohlstand** [comment] 2018-05-22 13:50
The thing I must to make is processing emulation in 53267 Hz, but resample the output into 44100 hz as requested on initialization of the emulator.

**Comment by papiezak** [comment] 2018-05-22 14:00
> But thanks for noting the internal sample rate value now I finally know
I took it from this thread: https://forums.nesdev.com/viewtopic.php?f=23&t=12772

I'm not as familiar with OPN2 as I'm with OPNA; that thing has 55466 Hz sample rate :wink:

**Comment by Wohlstand** [comment] 2018-05-25 16:00
Just now I made a small test: I have installed in my VLC properties to output OPNMIDI with 53267 hz, and sounding of  my ride cymbals in a same MIDI file now is matching Nuked OPN2!

**Comment by Wohlstand** [comment] 2018-06-03 16:11
@jpcima , as you just now have made the improved resampler on Nuked OPL3, it's also needed to be made here too, BUT, also, implement the simple resampler that will be used by default. It's need to output from MAME the 55466 hz, but do post-resampling. Then, emulator will almost-match by sounding with Nuked OPN2 and real chip.

**Comment by jpcima** [comment] 2018-06-03 16:27
Yeah let's do it. For the normal case i'll copy-paste linear resampling code of Nuked OPN in fixed point integers.

**Comment by jpcima** [comment] 2018-06-03 17:33
It's not all that straight-forward because MAME is not possible to drive by single frame generation. An attempt to do that is likely to make the processing cost go through the roof.
So, it is obligatory to introduce an intermediate buffering, and ideally a computation to know in advance how much frames to feed in the input to obtain N frames of output. And that with zita resampling, I don't know of a full reliable way to determine it.

**Comment by Wohlstand** [comment] 2018-06-03 21:12
MAME now does native sample rate! :fox_face: :+1: 
So, next stuff is optional HQ Zita Re-sampler work from @jpcima which he recently made into libADLMIDI :wink:

**Comment by jpcima** [comment] 2018-06-03 22:15
Do you consider the drums to be now fixed?
It's a note to myself, I should also also add the resampling option to Nuked like it was done in ADLMIDI.

**Comment by papiezak** [comment] 2018-06-04 14:00
Just checked out, it's alright now. Thanks to both of you! 
P.S.: about zita-resampler library; is there a windows version/build of that?

**Comment by jpcima** [comment] 2018-06-04 14:40
Yes building on MinGW is a triviality, but there isn't a ready build system for it in the source archive.
Also, I think Fons Adriaensen is no longer active on his projects, so one of us can fork this and make a build system for Windows, and release a set of binaries.

**Comment by Wohlstand** [comment] 2018-06-04 14:41
That probably can be made via CMake, and yeah, I'll even can make the repo and put zita-resampler into it with the CMake builder

**Comment by Wohlstand** [comment] 2018-06-04 14:46
I'll close this as the task has been completed and confirmed!
I'll copy the work over chips into OPN2 Bank Editor when I'll be at my home...

**Closed** 2018-06-04 15:07 UTC
Labels: enhancement

**Comment by Wohlstand** [comment] 2018-06-04 15:13
Oh, I wasn't closed it by mistake on a key.. But okay that you did that by yourself :wink:

**Comment by jpcima** [comment] 2018-06-04 16:34
@Wohlstand I did the Zita-resampler work so you just have to pull this in your repo.
The Pthread requirement was also removed so MSVC should be able to build.
https://github.com/jpcima/zita-resampler

**Comment by papiezak** [comment] 2018-06-04 16:44
Turns out it's not so trivial:
![fail](https://user-images.githubusercontent.com/32672779/40930191-440f5efc-6827-11e8-8e71-ddd7f532e494.PNG)

**Comment by Wohlstand** [comment] 2018-06-04 16:45
std::mutex needs for C++11 turned on. The CMake config @jpcima made uses the default behavior of given compiler as you can see.

**Comment by jpcima** [comment] 2018-06-04 16:45
Pull the very latest

**Comment by papiezak** [comment] 2018-06-04 16:54
still pretty much the same

**Comment by jpcima** [comment] 2018-06-04 16:58
Ok I'm going to backpedal and implement another strategy. I don't need c++11.

**Comment by jpcima** [comment] 2018-06-04 17:09
I've rewritten master with a version which is normally c++98 compatible. I can build it.

**Comment by papiezak** [comment] 2018-06-04 17:09
thanks @jpcima, pulled the very latest, now it compiles
