### ISSUE TITLE
Occassional messy playback (bug?)

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libOPNMIDI#45] opened 2018-06-26 11:46 UTC
High time I reported this issue.
There are few midis which break OPNMIDI. During playback, weird noises (sound like junk FM data?) can be heard in the background. Sometimes these are very loud and long and I can't really tell what is the real cause. At this point I can't tell it's emulation issue or broken GS support.
It affects both mine and your xg bank (although they are not as noticeable as in case of mine). 
What's really weird though it's that these noises happen at different time positions between VLC and command- line MIDI player ( I even suspect PGE MUSplay would give different result, one month ago it was the case). It's almost random.

[bug.zip](https://github.com/Wohlstand/libOPNMIDI/files/2136939/bug.zip) - here are recordings, two MIDs which exhibit that bug ,newest revision of my bank and a version of it with every instrument and drum muted so have this crap isolated on MIDI2.MID

P.S. It's somewhat better after sysex calls were implemented, so it could have something to do with NRPNs. But then again, they're ignored at this point :suspect:

**Comment by Wohlstand** [comment] 2018-06-26 12:06
PGE MusPlay here is still use old version (until I'll push the updates into AudioCodecs repository and will poke SDL Mixer X and PGE-Project pull the fresh deps)

**Comment by Wohlstand** [comment] 2018-06-26 12:07
About of the bug, I guess, it's arpeggio have applied to... percussion instruments! Damn!

**Comment by Wohlstand** [comment] 2018-06-26 13:22
But seems some another glitch, it's not an arpeggio, however, I'll check out the thing...

**Comment by papiezak** [comment] 2018-06-26 13:41
Yeah, it's not arpeggio, since libADLMIDI sounds rather fine.
Maybe YM2612 commands are called incorrectly, like in case of OPL3's drum mode...

**Comment by Wohlstand** [comment] 2018-06-26 14:00
Okay, I found reason why this happens: when all channels are busy, and when some of them (with note that begins playing now) are immediately overriding them (too short distance between first noteOn and second that overrides first)

**Comment by Wohlstand** [comment] 2018-06-26 14:15
Okay, after some tweaking: this will happen when one instrument will be missing!
I know how to resolve this - drop the note if no instrument on it

**Comment by Wohlstand** [comment] 2018-06-26 14:17
[opn2-singlechip-noise-on-missing-notes.mid.zip](https://github.com/Wohlstand/libOPNMIDI/files/2137505/opn2-singlechip-noise-on-missing-notes.mid.zip)
Just now I made the unit-test MIDI file that reproduces this crap, but, you need to turn the single-chip for this.

**Comment by Wohlstand** [comment] 2018-06-26 14:18
Lowest note here plays empty instrument entry.
![default](https://user-images.githubusercontent.com/6751442/41918366-e396affe-7964-11e8-9759-bfc03ef4f934.png)

**Comment by Wohlstand** [comment] 2018-06-26 14:39
So, the fix is - complete avoiding blank notes be even played. This will also resolve trouble of channels overflow that caused by those damned blank notes (are playing missing instrument).

**Comment by Wohlstand** [comment] 2018-06-26 14:57
Just now I have posted an update, please try it out!
I'll apply same to libADLMIDI as this will give more effective channels usage as blank notes will don't busy chip channels.

**Comment by Wohlstand** [comment] 2018-06-26 15:18
@papiezak , Try to test the stuff again

**Comment by papiezak** [comment] 2018-06-26 15:27
Sounds good so far. Please apply it to vlc plugin as well

**Comment by Wohlstand** [comment] 2018-06-26 15:29
VLC plugin is only a wrapper over the library which is an actual backend, so, the fix will affect everything that uses libADLMIDI, include VLC plugin :wink:

**Comment by papiezak** [comment] 2018-06-26 15:32
that's strange, at first I compiled vlc plugin, gave a listen to one of mids I sent and heard crap note

**Comment by Wohlstand** [comment] 2018-06-26 15:38
I think, you need to do full rebuild (`make clean` and then `make -j 4` again)

**Comment by papiezak** [comment] 2018-06-26 15:42
Yes, it's OK now.

**Comment by Wohlstand** [comment] 2018-06-26 15:57
Closing as fixed and tested! :fox_face: :+1:

**Closed by Wohlstand** 2018-06-26 15:57 UTC
Labels: bug
